stages:
- stage: Test
  jobs:
  - template: ./devtools/azure-pipelines-linux.yml
  - template: ./devtools/azure-pipelines-osx.yml
  - template: ./devtools/azure-pipelines-win.yml
  - template: ./devtools/azure-pipelines-conda.yml
