parameters:
- name: pythonVersion
  type: string
  default: 3.9
- name: numpyVersion
  type: string
  default: 1.21

steps:
- bash: |
    conda config --add channels conda-forge
    conda config --set always_yes true
    conda config --set quiet true
  displayName: Configure conda
- bash: |
    conda update --all
    conda install conda-build conda-verify pip
  displayName: 'Update and install dependencies'
  continueOnError: false
- template: checkout.yml
- bash: |
    conda build devtools --python ${{ parameters.pythonVersion }} --numpy ${{ parameters.numpyVersion }} -c pytorch
  displayName: 'Build and test'
  continueOnError: false
