steps:
  - bash: |
      conda config --add channels conda-forge
      conda config --set always_yes true
      conda config --set quiet true
    displayName: Configure conda
  - bash: |
      python -m pip install --upgrade pip
      conda update --all
    displayName: Update conda
  - bash: |
      conda install conda-build conda-verify pip
    displayName: 'Install dependencies'
    continueOnError: false
  - script: set PYTHONUNBUFFERED=1
      displayName: Set PYTHONUNBUFFERED
  - bash: |
      conda build devtools
    displayName: 'Build and test'
    continueOnError: false
