package:
  name: deeptime
  version: 0

source:
  path: ../..

build:
  script:
    - "{{ PYTHON }} -m pip install . -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - versioneer ==0.28
    - cython
    - scipy

  host:
    - python
    - cython
    - pip
    - scipy
    - toml
    - ninja
    - cmake >=3.18
    - numpy >=1.14
    - pybind11 >=2.9.0
    - scikit-build
    - versioneer ==0.28
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - threadpoolctl

test:
  imports:
    - deeptime
