package:
  name: deeptime
  #version: dev+{{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_DESCRIBE_NUMBER + '.' + GIT_DESCRIBE_HASH}}
  version: 0

source:
  path: ../..

build:
  skip: true  # [win and vc<14]
  script_env:
    - OMP_NUM_THREADS
    - AGENT_BUILDDIRECTORY
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip_compile_pyc:
    - "deeptime/util_torch.py"
    - "deeptime/decomposition/vampnet.py"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - intel-openmp # [osx]

  host:
    - cython
    - intel-openmp # [osx]
    - numpy >=1.14
    - python
    - scipy
    - setuptools !=50.0.0
    - pip
    - pybind11

  run:
    - intel-openmp # [osx]
    - vs2015_runtime  # [win]
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  source_files:
    - tests/*

  requires:
    - scikit-learn
    - pytest
    - pytest-cov
    - pytest-faulthandler
    - pytest-sugar
    - importlib_metadata  # [py<38]
    - typing_extensions  # [py<38]
    - mdshare
    - pytorch >=1.1
