package:
  name: scikit-time
  #version: dev+{{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_DESCRIBE_NUMBER + '.' + GIT_DESCRIBE_HASH}}
  version: 0

source:
  path: ../..
  #git_url: ../../

build:
  script_env:
   - OMP_NUM_THREADS
   - AGENT_BUILDDIRECTORY
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - intel-openmp # [osx]

  host:
    - cython
    - intel-openmp # [osx]
    - numpy
    - python
    - scipy
    - setuptools
    - pip

  run:
    - intel-openmp # [osx]
    - msmtools
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - pint

test:
  source_files:
    - tests/*
    # for doctests
    # - sktime/*
  requires:
    - scikit-learn
    - pytest
    - pytest-cov
    - pytest-faulthandler
    - pytest-sugar
    - mdshare
