package:
  name: pyemma-dev
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' +GIT_BUILD_STR}}
source:
  path: ../..

build:
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython >=0.20
    - mdtraj >=1.8
    - numpy x.x
    - python
    - scipy
    - setuptools
  run:
    - bhmm >=0.6,<0.7
    - decorator >=4.0.0
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.7
    - mock
    - msmtools >=1.2
    - numpy x.x
    - progress_reporter <=1.2
    - psutil >=3.1.1
    - python
    - pyyaml
    - scipy
    - setuptools
    - six >=1.10
    - thermotools >=0.2.3

test:
  requires:
    - pytest 
    - pytest-cov
  imports:
    - pyemma

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"


