package:
  name: pyemma-dev
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_BUILD_STR}}
source:
  path: ../..
  # borked, but preferable, because it creates a "clean" working copy locally.
  #git_url: ../../

build:
  preserve_egg_dir: True
  script_env:
   - CIRCLE_TEST_REPORTS
   - OMP_NUM_THREADS

requirements:
  build:
    - cython
    - gcc # [linux or osx]
    - mdtraj
    - numpy x.x
    - pybind11
    - python
    - scipy
    - setuptools
  run:
    - bhmm >=0.6,<0.7
    - decorator >=4.0.0
    - h5py
    - joblib >0.8.4
    - libgcc # [linux or osx]
    - matplotlib
    - mdtraj
    - mock
    - msmtools >=1.2
    - numpy x.x
    - progress_reporter
    - psutil >3.1
    - python
    - pyyaml
    - pathos
    - scipy
    - setuptools
    - six >=1.10
    - thermotools >=0.2.6

test:
  commands:
  # enable the reporting of Python warning
    - pip install pytest-warnings
  source_files:
    - conftest.py
    - setup.cfg
  files:
    - matplotlibrc
  requires:
    - pytest
    - pytest-cov
    - pytest-faulthandler

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"
